language: crystal
dist: trusty
sudo: false
addons:
  apt:
    packages:
before_install: crystal deps
install: crystal build --release src/*.cr
deploy:
  provider: releases
  api_key:
    secure: GITHUB_TOKEN
    file: "load-file"
    skip_cleanup: true
    on:
      branch: master
